name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - '**'

jobs:
  build_and_deploy_job:
    if: github.ref == 'refs/heads/main' || github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MUD_029B08703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "." # App source code path
          api_location: "" # Api source code path - optional
          output_location: "." # Built app content directory - optional
