name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - dev-main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm cache clean --force
      - run: npm ci
      - run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin gh-pages:gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

          git rm -rf .

          cp -r dist/* .

          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages