name: Node.js CI

on:
  push:
    branches:
      - main
      - dev-main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          # Ensure we have the latest version of the deploy branch
          git fetch origin gh-pages:gh-pages
          # Switch to the deploy branch
          git checkout gh-pages
          # Copy build files to the root
          cp -r build/* .
          # Add all changes
          git add .
          # Commit the changes
          git commit -m "Deploy to GitHub Pages"
          # Push to the deploy branch
          git push origin gh-pages